version: '3'
networks: 
development:
test:
volumes:
db_data:
gem_cache:
shared_data:
sevices:
  restarone_db:
   image: postgres:14.5-alpine
   container_name: raedah_finance_ruby_devise_db

volumes: 
   - db_data:/var/lib/postgresql/db_data
   - shared_data:/var/shared 
networks:
- development
- test

environment:
POSTGRES_USER: postgres
POSTGRES_PASSWORD: password
ports:
-  5099:5432
raedah_finance_ruby_devise_app:
 build:
  context: .
  dockerfile: Dockerfile.dev
container_name: raedah_finance_ruby_devise_app

volumes:

  - .:/var/app
  - shared_data:/var/shared
  - gem_cache:/usr/local/bundle/gems

networks:
  development
ports:
-  3000:3000
stdin_open: true
tty: true
env_file: .env.development
entrypoint: dev-entrypoint.sh
command: ['rails', 's', '-p', '3000', '-b', '0.0.0.0']
environment:
RAILS_ENV: development
depends on:configs:
- raedah_finance_ruby_devise
raedah_finance_ruby_devise_test:
image: raedah_finance_ruby_devise_raedah_finance_ruby_devise_app
container_name: raedah_finance_ruby_devise_test
volumes:
   - .:/var/app
   - shared_data:/var/shared
   - gem_cache:/usr/local/bundle/gems
networks:
   test:
 ports:
 - 3001:3000
stdin_open: true
tty: true
env_file: .env.test
entrypoint: test-entrypoint.sh
command: ["rails", "-v"]
environment:
RAILS_ENV: TEST
depends_on:
- raedah_finance_ruby_devise_db

